---
title: "Run Association models"
output: html_notebook
---

```{r}
library(tidyverse)
library(data.table)
library(rstatix)
library(parallel)
library(qqman)
library(doParallel)
library(ape)
```

```{r}
# Load covariates
rootDir <- "/workdir/coh22/poaceae_tfbs/"
metadata <- read.table(paste0(rootDir, "data/Poaceae_metadata_filtered_2025.04.16.tsv"), sep = "\t")
env <- read.table(paste0(rootDir, "output/modelData/envData_759Poaceae_20240821.txt")) %>%
  mutate(assemblyID = rownames(.))
phyloK <- read.table(paste0(rootDir, "output/modelData/phyloK_728Poaceae_astral_20250407.txt"))
tree <- read.tree(paste0(rootDir, "output/modelData/PoaceaeTree_angiosperm353_astral_filtered_20250407.nwk"))
colnames(phyloK) <- rownames(phyloK)
```

Calculate environmental residuals for ePC1 after controlling for phylogeny
``` {r}
library(asreml)
env_for_model <- mutate(env, assemblyID = as.factor(assemblyID))
envPC1_phyloK <- asreml(envPC_1 ~ 1, random = ~ vm(assemblyID, phyloK), ai.sing = TRUE, data = env_for_model)
# Calculate variance explained by phylogeny
modelSummary <- summary(envPC1_phyloK)
phylo_explained <- modelSummary$varcomp$component[1] / sum(modelSummary$varcomp$component[1:2]) # 89% explained

# Write resids to file
envPC1_resids <- residuals(envPC1_phyloK)
names(envPC1_resids) <- env$assemblyID
write.table(envPC1_resids, file = "/workdir/coh22/andro_tfbs/results/models/envPC1_resids.txt", col.names = F, quote = F)
```

``` {r}
# Load unenriched clusters to filter out
unenriched_clusters <- read.table("/workdir/coh22/poaceae_tfbs/lists/unenriched_clusters.txt", header = F)
# Load motif cluster metadata
cluster.meta <- read.table("/workdir/coh22/poaceae_tfbs/data/JASPAR2024_SummarizedClusters.txt") %>%
  dplyr::select(TF = V3, cluster = V2) %>%
  dplyr::filter(!TF %in% unenriched_clusters$V1)  %>% # Filter out clusters that are not enriched across Poaceae 
  arrange(TF) # Alphabetize

# Load motifs
# Prepare to iterate through directory to load motif data
files <- list.files("/workdir/coh22/poaceae_tfbs/output/motifOutput/motifs_by_orthogroup/filtered_OGs_200assemblies", full.names = TRUE)
n_ortho <- sum(file.info(files)$isdir == FALSE)
mat.list <- list()

# Load motifs
cl <- makeCluster(detectCores())
clusterExport(cl, c("files", "n_ortho", "cluster.meta"))
mat.list <- parLapply(cl, 1:n_ortho, function(i) {
  # Import libraries in each cluster node
  library(data.table)
  library(dplyr)
  library(tidyr)
  
  motifCounts <- fread(files[[i]]) %>%
    dplyr::select(c(cluster = V2, ogID = V3, motifCount = V4, assemblyID = V5)) %>%
    dplyr::left_join(cluster.meta) %>%
    dplyr::select(-cluster) %>%
    dplyr::distinct(across(c(assemblyID, TF)), .keep_all = TRUE) %>%
    pivot_wider(names_from = TF, values_from = motifCount)
  
  # Identify any missing TF clusters not present in motifCounts
  missing_TFs <- setdiff(cluster.meta$TF, colnames(motifCounts))
  # Add missing TF cluster columns with NA values
  motifCounts[missing_TFs] <- as.integer(NA)
  # Set column names to cluster.meta$TF
  motifCounts <- motifCounts %>%
    dplyr::select(assemblyID, ogID, all_of(cluster.meta$TF))
  
  # Replace NA values with zeros
  motifCounts <- motifCounts %>%
    dplyr::mutate(across(where(is.numeric), ~replace_na(., 0)))
  
  mat <- motifCounts[,3:ncol(motifCounts)] %>%
    as.matrix()
  rownames(mat) <- motifCounts$assemblyID
  return(mat)
})

stopCluster(cl)
names(mat.list) <- gsub(".*/([^/]+)\\.txt", "\\1", files) # Annotate with OG IDs

```


Run orthogroup-specific models with asreml
``` {r}
Run_MLMs_OrthoSpecific <- function(Kphylo, EnvTraitMatrix, motifMatList) {
    # Check if the file exists and remove it before the loop
    filename <- "/workdir/coh22/poaceae_tfbs/output/output_log.txt"
    if (file.exists("/workdir/coh22/poaceae_tfbs/output/output_log.txt")) {
        file.remove(filename)
    }
    # Custom logging function to append to a file with timestamps
    log_to_file <- function(text, filename = "/workdir/coh22/poaceae_tfbs/output/output_log.txt") {
      timestamp <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")
      write(paste(timestamp, text), file = filename, append = TRUE)
    } 
    ePC_names <- colnames(EnvTraitMatrix)

  nOrtho <- length(motifMatList)
  cl <- makeCluster(2) # create cluster
  registerDoParallel(cl)
  results <- foreach(i = 1:nOrtho, .combine = 'c') %dopar% {
    library(dplyr)
    library(asreml)
    library(data.table)
    asreml.options(verbose = FALSE)
    ogID <- names(motifMatList)[i]
    
    log_to_file(paste("Running models for", ogID, "..."))
    motifMatrix <- motifMatList[[i]] # Get motif matrix for ith orthogroup
    n_traits <- ncol(EnvTraitMatrix)
    nMotifs <- ncol(motifMatrix) # get number of motifs represented in at least one species for this orthogroup
    # Find common taxa represented in motif, phyloK, and environment datasets
    common_rows <- base::intersect(rownames(motifMatrix), rownames(Kphylo)) %>% 
        base::intersect(rownames(EnvTraitMatrix)) %>%
        sort()

    # Filter to retain taxa shared across datasets
    EnvTraits_filtered <- EnvTraitMatrix[common_rows,]
    motifMat_filtered <- motifMatrix[common_rows,]
    phyloK_filtered <- Kphylo[common_rows,common_rows]
    input_matrix <- as.data.frame(cbind(EnvTraits_filtered, motifMat_filtered))
    input_matrix$assemblyIDs <- factor(common_rows)

    setnames(input_matrix, gsub("-", "_", names(input_matrix))) # Remove hyphens from motif names to enable parsing by model
    colnames(input_matrix)[1:ncol(EnvTraitMatrix)] <- ePC_names
    ## Iterate over all motifs in matrix
    motifModels <- list()
    for(j in 1:nMotifs){
    motifID <- colnames(input_matrix)[j+n_traits]
    # Check if more than 1 unique value
    if(length(unique(motifMat_filtered[,j])) > 1) {
        # Run association model for each motif
        formula_str <- paste(motifID, "~", paste(ePC_names, collapse =" + "), collapse = " ")
        formula_obj <- as.formula(formula_str)
        # Model fitting
        result <- tryCatch({
            model <- asreml(
                fixed = formula_obj,
                random = ~ vm(assemblyIDs, phyloK_filtered),
                ai.sing = TRUE,
                data = input_matrix
            )
            # Extract model results
            modelSummary <- summary(model)
            loglik <- modelSummary$loglik
            phylo_explained <- modelSummary$varcomp$component[1] / sum(modelSummary$varcomp$component[1:2])
            modelWald <- wald.asreml(model)
            env_coeffs <- model$coefficients$fixed[2:(1 + n_traits)]
            env_pval_log10p <- -(pchisq(modelWald[(2:(1 + n_traits)), 3], 1, log.p = TRUE, lower.tail = FALSE) / log(10))

            env_coeffs <- if (length(env_coeffs) == n_traits) env_coeffs else rep(NA, n_traits)
            env_pvals_log10p <- if (length(env_pval_log10p) == n_traits) env_pval_log10p else rep(NA, n_traits)

            list(ogID, motifID, phylo_explained, env_coeffs, env_pvals_log10p)
        }, error = function(e) {
            log_to_file(paste("Error running model for", motifID, "in", ogID, ":", e$message))
            list(ogID, motifID, NA, rep(NA, times = n_traits), rep(NA, times = n_traits)) # Return NA for results
        })
        motifModels[[j]] <- result
    }    
    else{
        # Do not run models and assign NA  to results if no variation in motif counts
        phylo_explained <- NA 
        env_coeffs <- rep(NA, times = n_traits)
        env_pvals_log10p <- rep(NA, times = n_traits)
        }
    motifModels[[j]] <- list(ogID, motifID, phylo_explained, env_coeffs,  env_pvals_log10p)    
    }
    motifModels
  }
  stopCluster(cl)
  return(results)
}

# Must supply named cols/rows with assembly IDs
EnvTraitMatrix <- env[,286:295] # first 10 ePCs
#EnvTraitMatrix <- env[,286:287] # first 2 ePCs
rownames(EnvTraitMatrix) <- env$assemblyID
models_phyloK_envPC1.10_poaceae_1_5000<- Run_MLMs_OrthoSpecific(phyloK, EnvTraitMatrix, mat.list[1:5000])
save(models_phyloK_envPC1.10_poaceae_1_5000, file="/workdir/coh22/poaceae_tfbs/results/models/models_phyloK_envPC1.10_poaceae_1_5000.RData")
```


```{r}
# Load models
n_pc <- 10
load("/workdir/coh22/poaceae_tfbs/output/models/models_phyloK_envPC1.10_poaceae_1_5000.RData")
load("/workdir/coh22/poaceae_tfbs/output/models/models_phyloK_envPC1.10_poaceae_5001_15555.RData")

cat_models <- c(models_phyloK_envPC1.10_poaceae_1_5000, models_phyloK_envPC1.10_poaceae_5001_15555) %>%
   lapply(unlist)

model_output <- mclapply(cat_models, function(x) {
  x <- t(x)
  x <- as.data.frame(x)
  names(x) <- c("OG", "motif", "phylo_explained", paste0("coef_ePC", 1:n_pc), paste0("log10pval_ePC", 1:n_pc))
  return(x)
}, mc.cores = detectCores() - 1)

# Identify models in which three or fewer taxa contain the motif (to filter out from results)
sparse_motifs <- do.call(rbind, lapply(names(mat.list), function(matrix_name) {
  mat <- mat.list[[matrix_name]]
  low_nonzero_rows <- which(apply(mat, 2, function(x) sum(x != 0)) < 4)
  if (length(low_nonzero_rows) > 0) {
    data.frame(OG = matrix_name, motif = colnames(mat)[low_nonzero_rows], stringsAsFactors = FALSE)
  } else {
    NULL
  }
}))

results <- rbindlist(model_output, fill = T)# %>%
head(results)
results_df <- results %>%
  pivot_longer(
    cols = starts_with("coef") | starts_with("log10pval"),
    names_to = c(".value", "ePC"),
    names_pattern = "(coef|log10pval)_ePC(\\d+)"
  ) %>%
  arrange(OG, motif, ePC) %>%
  as.data.frame() %>%
  dplyr::filter(phylo_explained < 0.95) %>% # Filter out models where motifs are too highly explained by phylogeny
  dplyr::anti_join(sparse_motifs, by = c("OG", "motif")) # filter out sparse motif-OG combinations

results_df[,c(3,5,6)] <- lapply(results_df[,c(3,5,6)], as.numeric)
results_df$pval <- 10^(-results_df$log10pval)
results_df$p.fdr <- p.adjust(results_df$pval, method = "fdr")
sorted_results <- arrange(results_df, desc(log10pval))

# How many motifs/OGs are significant?
sig_motif_ogs <- dplyr::filter(results_df, p.fdr < 0.01) %>%
  dplyr::select(c(OG, motif)) %>%
  unique()

# Compare p value boxplots
ggplot(results_df, aes(x = factor(ePC), y = log10pval)) +
  geom_boxplot() +
  labs(
    title = "Distribution of -log10(p) values by ePC",
    x = "ePC",
    y = "-log10(p)"
  ) +
  theme_minimal()
```

Function to make QQ plot 
```{r}
PlotQQ <- function(df) {
  # Create observed vs expected p values for plot
  observed_pvals = sort(df$log10pval, decreasing = T)
  observed_p.fdr = p.adjust(10^(-observed_pvals), method = "fdr")
  expected_pvals = qunif(seq(0, 1, length.out = length(observed_pvals) + 2), min = 0, max = 1)  ## Generate expected values. Note that we are using length+2
  expected_pvals = expected_pvals[expected_pvals != 0 & expected_pvals != 1]  ## Remove the two extra values since they are 0 and 1

  p_df = data.frame(observed = observed_pvals,
                    expected = -log10(expected_pvals),
                    color = ifelse(observed_p.fdr < 0.01, "goldenrod1", "#2C7BB6"))  # Assign color based on p.fdr
  
  ggplot(p_df, aes(x = expected, y = observed, color = color)) +
    geom_point(size = 7, alpha = 0.8) +  # Color determined by 'color' column
    scale_color_identity() +  # Use color values directly
    geom_abline(intercept = 0, slope = 1, color = '#D7191C', linetype = 'dashed', linewidth = 0.8) +  # Dashed red line
    labs(
      x = expression("-log"[10]~"Expected p-value"),
      y = expression("-log"[10]~"Observed p-value")
    ) +
    theme_minimal(base_size = 36) +  # Minimal theme for clean appearance
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold"),  # Center and bold title
      axis.title = element_text(face = "bold"),  # Bold axis titles
      panel.grid.major = element_line(linewidth = 0.5, color = 'grey80'),  # Light gray grid lines
      panel.grid.minor = element_blank()  # Remove minor grid lines
    )
}

PlotQQ_sampled <- function(results_df, frac = 0.01) {
  df_sampled <- results_df[sample(nrow(results_df), size = max(10000, round(nrow(results_df) * frac))), ]  # Keep max(10000 or frac)
  PlotQQ(df_sampled)
}

PlotQQ_sampled(results_df)

# Save full
ggsave("/workdir/coh22/poaceae_tfbs/results/models/qqplot_envPC1_10_perOG_p01.png", plot = PlotQQ(results_df), width = 10, height = 10, dpi = 300)
```

Look at top hits
``` {r}
maize_gene_desc <- read.table("/workdir/coh22/poaceae_tfbs/output/go_enrichment/B73_DE.out", sep = "\t", header = TRUE, quote="", fill=TRUE) %>%
  dplyr::select(c(qpid, desc)) %>%
  mutate(ZmID = sapply(qpid, function(x) strsplit(x, "_")[[1]][1])) %>%
  group_by(ZmID) %>%
  dplyr::summarise(desc = paste(unique(desc), collapse = "; ")) %>%
  mutate(desc = str_replace(desc, "\t", ";"))

OGkey <- read.table("/workdir/coh22/poaceae_tfbs/output/ogs/OGToZm_mapping_v2.txt") %>%
  dplyr::rename(c(ZmID = V1, OG = V2)) %>%
  mutate(ZmID = sapply(ZmID, function(x) strsplit(x, "_")[[1]][1])) %>%
  left_join(maize_gene_desc)

View(left_join(sorted_results[1:1000,], OGkey))

focal_ePC <- dplyr::filter(results_df, ePC == "1")
#focal_ePC <- dplyr::filter(results_df, ePC == "2")
PlotQQ(focal_ePC)
focal_ePC[order(focal_ePC$log10pval, decreasing = T),][1:100,] %>%
  left_join(OGkey) %>%
  write.table("/workdir/coh22/poaceae_tfbs/results/models/envPC1_top_hits_OGspecific.txt", quote = T, row.names = F, sep = "\t")

# How many have pvals <1e-5?

#top_hits <- dplyr::filter(results_df, log10pval > 5) %>%
#bin_length <- round(nrow(results_df) * 0.001) # top 0.1% of hits
top_hits <- results_df[order(results_df$log10pval, decreasing = T),][1:1025,] %>%
#top_hits <- focal_ePC[order(focal_ePC$log10pval, decreasing = T),][1:100,] %>%
  left_join(OGkey)

View(top_hits)

write.csv(top_hits, "/workdir/coh22/poaceae_tfbs/results/models/top_hits_OGspecific.csv", quote = T, row.names = F)
```

Plot candidate motifs/OGs on phylogeny
``` {r}
source("/workdir/coh22/poaceae_tfbs/src/09_envirotyping/PlotTraitsOnTree.R")
candidate.mat <- as.data.frame(mat.list["OG0018131"])

env <- read.table("/workdir/coh22/poaceae_tfbs/output/modelData/envData_759Poaceae_20240821.txt") %>%
  mutate(assemblyID = rownames(.))

plotTraitOnTree(trait = candidate.mat$OG0018131.HSF_GARP, taxa = rownames(candidate.mat), tree = tree, visible_tip_labels = T, shape = "phylogram", colors = c("white", "black"))

candidate.counts <- as.data.frame(cbind(candidate.mat$OG0018131.HSF_GARP, rownames(candidate.mat))) %>%
  setnames(c("motifCount", "assemblyID"))

all_rep_taxa <- left_join(candidate.counts, env)

all_rep_taxa_binarized <- all_rep_taxa %>%
  mutate(motifCount = ifelse(as.numeric(motifCount) > 1, 1, 0))

# For categorical relationship with motif count
ggplot(all_rep_taxa_binarized, aes(x = motifCount, y = envPC_1, fill = motifCount, group = motifCount)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "HSF_GARP motif presence upstream of OG0018131", x = "HSF_GARP presence", y = "Environmental PC1")

# For quantitative variation in motif count
ggplot(all_rep_taxa, aes(x = factor(motifCount), y = envPC_1)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.5, fill = "lightblue") + # Boxplot with transparency
  geom_jitter(width = 0.2, size = 5, alpha = 0.7, color = "blue") + # Jittered points
  labs(x = "HSF/GARP Motif Count, OG0018131", y = "Environmental PC1") +
  theme_minimal(base_size = 36)

# Taxa with more than 2 copies of the motif
top_taxa <- filter(all_rep_taxa, as.numeric(motifCount) > 2) %>% 
  left_join(metadata) %>%
  dplyr::select(c(Species, assemblyID, envPC_1, motifCount))
```

GO enrichment
```{r}
library(topGO)
mappingFile = read.table("/workdir/coh22/poaceae_tfbs/output/ogs/OGToZm_mapping_v2.txt") %>% # map to maize
   mutate(V1=sapply(V1, function(x) strsplit(x, "_")[[1]][1])) # For maize

all_ogs <- unique(mappingFile[mappingFile[,2]%in%names(mat.list),1])
top_ogs = unique(mappingFile[mappingFile[,2]%in%unique(top_hits$OG),1])

GODB <- readMappings("/workdir/coh22/poaceae_tfbs/output/go_enrichment/Zm00001eb.1.fulldata_goList.txt",IDsep = ",")
background = intersect(names(GODB),all_ogs)
tmp=factor(as.integer(background%in%top_ogs))
names(tmp)=background

# Define a function to process each ontology
algo <- "weight01" # Choose topGO algorithm
process_topGO <- function(ontology, allGenes, GODB, top_ogs, mappingFile) {
  tgd1 <- new("topGOdata", ontology = ontology, allGenes = allGenes, nodeSize = 5, annot = annFUN.gene2GO, gene2GO = GODB)
  resTopGO <- runTest(tgd1, algorithm = algo, statistic = "Fisher")
  GO_res_table <- GenTable(tgd1, pval = resTopGO, orderBy = "pval", 
                           ranksOf = "pval", topNodes = length(resTopGO@score), numChar = 100)
  GO_res_table$sigGenes <- sapply(GO_res_table[, 1], function(x) {
    paste(mappingFile[mappingFile[, 1] %in% intersect(top_ogs, genesInTerm(tgd1, x)[[1]]), 2], collapse = ",")
  })
  GO_res_table_df <- as.data.frame(GO_res_table)
  
  # Filtering and transformation
  significant_results <- GO_res_table_df %>%
    #mutate(Fisher.FDR = p.adjust(as.numeric(pval), method = "fdr")) %>%
    filter(pval < 0.05) %>%
    mutate(neglog10Fisher = -log10(as.numeric(pval))) %>%
    arrange(desc(neglog10Fisher))
  
  # Add ontology information
  significant_results <- significant_results %>%
    mutate(Ontology = ontology) %>%
    mutate(enrichment = Significant / Expected)
  
  return(significant_results)
}

# Process each ontology
significant_BP <- process_topGO("BP", tmp, GODB, top_ogs, mappingFile)
significant_MF <- process_topGO("MF", tmp, GODB, top_ogs, mappingFile)
significant_CC <- process_topGO("CC", tmp, GODB, top_ogs, mappingFile)

# Merge results
merged_results <- bind_rows(significant_BP, significant_MF, significant_CC) %>%
  arrange(desc(neglog10Fisher))

#View(merged_results_most_conserved[,c(2,4,5,8,9)])
View(merged_results[,c(2,3,4,5,6,8,10)])
top_terms <- merged_results[1:7,]
#top_terms <- significant_MF[1:6,]
top_terms$Term <- sapply(top_terms$Term, function(x) substr(x, 1, 30)) # Truncate terms to make plotting prettier
# Create the bubble plot
ggplot(top_terms, aes(
  x = neglog10Fisher, 
  y = reorder(Term, neglog10Fisher), 
  size = Significant, 
  color = enrichment
)) +
  geom_point(alpha = 0.7) +
  scale_x_continuous(limits = c(1.5, 3)) +
  scale_color_gradient(low = "red", high = "blue", limits = c(1, 12)) +
  scale_size(range = c(10, 40)) +  # This line affects bubble size
  labs(
    x = "-log10(Fisher)", 
    y = NULL, # Remove axis title for y to match your example
    size = "Significant",
    color = "Enrichment"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 10), # Adjust text size for better visibility
    axis.title.x = element_text(size = 12),
    legend.position = "right",
    panel.grid.major.y = element_line(size = 0.5, color = "grey80"), # Add gridlines for alignment
    plot.title = element_text(hjust = 0.5, size = 14))

write.csv(merged_results[,c(2,3,4,5,6,8,10)], "/workdir/coh22/poaceae_tfbs/results/models/GO_topAssociationModelHits.csv", quote = F, row.names = F)
```


Investigate whether RAOs from Yeaman 2024 are found in top hits
``` {r}
raos <- read.table("/workdir/coh22/andro_tfbs/output/turnover_analysis/env_turnover/Yeaman2024RAO_OGID.txt")
names(raos) <- c("At_id", "OG")
unique_top_ogs <- unique(top_hits$OG)
# Which OGs are there?
dplyr::filter(top_hits, OG %in% unique_top_ogs[unique_top_ogs %in% raos$OG])
prop_rao_total <- nrow(raos) / n_ortho
prop_rao_top <- length(unique_top_ogs[unique_top_ogs %in% raos$OG]) / length(unique_top_ogs)
```





