---
title: "Conservation of motif enrichment within regulatory regions"
author: "Charlie Hale"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
options(scipen = 20)
library(stats)
library(VennDiagram)
library(tidyverse)
library(pheatmap)
library(UpSetR)
library(data.table)
library(fitdistrplus)
library(parallel)

# Set the root directory for the project
rootDir <- "/workdir/coh22/poaceae_tfbs/"
source(paste0(rootDir, "src/05_motifEnrichment/CalculateMotifEnrichment.R"))

nCores <- 10
```

```{r load_data}
focal_species <- c("Zea_mays", "Hordeum_vulgare", "Oryza_sativa", "Sorghum_bicolor", "Brachypodium_distachyon")
# Load motif metadata
grass_taxa <- c("Zea mays", "Hordeum vulgare", "Triticum aestivum", "Oryza sativa Japonica Group", "Oryza sativa Indica Group", "Oryza sativa") # to subset motifs that were characterized in grasses
plant_motif_key <- read.table("/workdir/coh22/poaceae_tfbs/data/JASPAR2024_CORE_plants_nr_PFM_key.txt", header = T, sep = "\t") %>%
  dplyr::rename(motif_id = MatrixID) #%>%
  #dplyr::filter(!SpeciesName %in% grass_taxa)
  # retain only motifs characterized in grasses
plant_motif_list <- dplyr::select(plant_motif_key, motif_id)

# Load the motif scanning data
for (species in focal_species) {
  emp_dir <- paste0(rootDir, "output/motif_enrichment/umrs_crisp2020/fimo/", species, "/empirical_fimo/filt_neg/")
  bg_dir <- paste0(rootDir, "output/motif_enrichment/umrs_crisp2020/fimo/", species, "/bg_fimo/filt_neg/")
  
  enrich_results_list_counts <- mclapply(plant_motif_list$motif_id, function(motif_id) {
    tryCatch({
      result <- calculateMotifEnrichment(motif_id, emp_dir, bg_dir, method = "counts")
      if (!is.null(result)) {
        return(result)
      }
    }, error = function(e) {
      message(paste("Error processing motif:", motif_id, "in species:", species))
      return(NULL)
    })
  }, mc.cores = nCores)

  # Combine all non-null vectors into a data frame
  enrich_results_df_counts <- do.call(rbind, enrich_results_list_counts[!sapply(enrich_results_list_counts, is.null)]) %>%
    as.data.frame() %>%
    setNames(c("motif_id", "emp_score", "bg_mean", "bg_sd", "p.value", "fold_change", "method")) %>%
    mutate(across(2:(ncol(.)-1), as.numeric)) %>%
    mutate(p.adj = p.adjust(p.value, method = "fdr")) %>%
    mutate(species = species) %>%
    dplyr::filter(emp_score != 0 & bg_mean != 0) # Remove undetectable motifs or motifs with negative scores
}

```

Correlate quantitative enrichment with previous presence/absence enrichment
``` {r}
maize_comparison <- enrich_results_df_counts %>%
  dplyr::select(c(motif_id, fc_counts = fold_change)) %>%
  inner_join(enrich_results_df_scores, by = "motif_id") %>%
  dplyr::rename(fc_scores = fold_change) %>%
  filter(fc_scores < 10)

ggplot(maize_comparison, aes(x = fc_counts, y = fc_scores)) +
  geom_point(alpha = 0.3, size = 3) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red") +
  labs(
    x = "Fold enrichment (counts method)",
    y = "Fold enrichment (scores method)",
    title = "Maize UMR enrichment correlation for motif counts vs motif scores"
  ) +
  theme_minimal()

fit <- lm(fc_scores ~ fc_counts, data = maize_comparison)
summary(fit)
```
