---
title: "Calculate and plot motif enrichment in maize regulatory features"
author: "Charlie Hale"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
options(scipen = 20)
library(stats)
library(tidyverse)
library(pheatmap)
library(data.table)
library(fitdistrplus)
library(parallel)

# Set the root directory for the project
rootDir <- "/workdir/coh22/poaceae_tfbs/"
source(paste0(rootDir, "src/05_motifEnrichment/CalculateMotifEnrichment.R"))

nCores <- 10
```

```{r load_data}
features <- c("umrs_crisp2020", "cns", "moa", "scATAC")
feature_files <- c("Zea_mays_B73v5", "panand_cns", "MOA_all_peaks.merged.21_NAMs_new0624", "Marand_scATAC_allCellTypes_B73v5")
plant_motif_key <- read.table("/workdir/coh22/poaceae_tfbs/data/JASPAR2024_CORE_plants_nr_PFM_key.txt", header = T, sep = "\t") %>%
  dplyr::rename(motif_id = MatrixID) #%>%
plant_motif_list <- dplyr::select(plant_motif_key, motif_id)
umr.enriched.motifs <- read.table(paste0(rootDir, "results/TableS1_UMR_enriched_motifs.csv"), sep = ",", header = T)
# Load motif scanning data
dfs_by_feature <- vector("list", length(features))
names(dfs_by_feature) <- features

for(i in seq_along(features)) {
  emp_dir <- paste0(rootDir, "output/motif_enrichment/", features[i],
                    "/fimo/", feature_files[i], "/empirical_fimo/")
  bg_dir  <- paste0(rootDir, "output/motif_enrichment/", features[i],
                    "/fimo/", feature_files[i], "/random_bg_fimo/")

  # Compute enrichment for each motif
  enrich_results_list_counts <- mclapply(plant_motif_list$motif_id, function(motif_id) {
    tryCatch({
      result <- calculateMotifEnrichment(motif_id, emp_dir, bg_dir, method="counts")
      if(!is.null(result)) result
    }, error=function(e){
      message("Error processing motif:", motif_id, "in species:", species)
      NULL
    })
  }, mc.cores=nCores)

  # Clean up results and merge into a single df
  df <- do.call(rbind, enrich_results_list_counts[!sapply(enrich_results_list_counts, is.null)]) %>%
    as.data.frame() %>%
    setNames(c("motif_id","emp_score","bg_mean","bg_sd","p.value","fold_change","method")) %>%
    mutate(across(2:(ncol(.)-1), as.numeric),
           p.adj = p.adjust(p.value, method="fdr"),
           feature = features[i]) %>%
    filter(emp_score != 0, bg_mean != 0)

  # Store in list
  dfs_by_feature[[i]] <- df
}

# Combine into a single df
enrich_by_feat_df <- rbindlist(dfs_by_feature)

# write results to csv
write.table(enrich_by_feat_df, file = paste0(rootDir, "results/maize_feature_enrichment.csv"), sep =",", quote = F)
```
Visualize results
``` {r}
enrich_by_feat_df <- read.table("/workdir/coh22/poaceae_tfbs/results/maize_feature_enrichment.csv", sep = ",") %>%
  mutate(log2_fc = log2(fold_change)) %>%
   dplyr::select(motif_id, log2_fc, feature) %>%
  pivot_wider(
    id_cols    = feature,
    names_from = motif_id,
    values_from = log2_fc
  ) %>%
  as.data.frame() 

# only motifs that are umr enriched
umr.enriched <- enrich_by_feat_df[,c("feature", umr.enriched.motifs$motif_id)]
  
mat <- umr.enriched %>% 
  column_to_rownames("feature") %>% 
  as.matrix()

pheatmap::pheatmap(
  mat,
  cluster_rows = TRUE,
  cluster_cols = TRUE,
  scale = "none",
  color = colorRampPalette(c("blue", "white", "red"))(100),
  breaks = seq(-2.1, 2.1, length.out = 101), 
  xlab = "Motif name",
  ylab = "Enrichment (log2)",
  main = "Motif enrichment within maize cis-regulatory features")



```