---
title: "Run global association models"
output: html_notebook
---
```{r, echo = F}
knitr::opts_chunk$set(
  fig.width = 10,  # Set the desired width
  fig.height = 6,  # Set the desired height
  dpi = 1000        # Set the resolution to 300 DPI
)
```

```{r, echo = F}
library(data.table)
library(rstatix)
library(parallel)
library(doParallel)
library(ape)
library(tidyverse)
library(ade4)
```

```{r}
# Load covariates
rootDir= "/workdir/coh22/poaceae_tfbs/"
# Load metadata
metadata <- read.csv(paste0(rootDir, "data/Poaceae_metadata_filtered_2025.04.16.tsv"))

# Load environmental data and add assemblyID
env <- read.table(paste0(rootDir, "output/modelData/envData_759Poaceae_20240821.txt")) %>%
  mutate(assemblyID = rownames(.))

# Load phylogenetic K matrix
phyloK <- read.table(paste0(rootDir, "output/modelData/phyloK_728Poaceae_astral_20250407.txt"))
colnames(phyloK) <- rownames(phyloK)

# Load phylogenetic tree
tree <- read.tree(paste0(rootDir, "output/modelData/PoaceaeTree_angiosperm353_astral_filtered_20250407.nwk"))

# Load nucleotide frequencies
nucFreqs <- read.csv(paste0(rootDir, "output/modelData/nucFreqs_shortIntrons.csv"))
```

``` {r}
# Motifs
source(paste0(rootDir, "src/07_motifTurnover/load_motif_data.R"))  # Adjust the filename as needed
mat.list <- load_motif_data(
  unenriched_clusters_path = paste0(rootDir, "lists/unenriched_clusters.txt"),
  cluster_meta_path = paste0(rootDir, "data/JASPAR2024_SummarizedClusters.txt"),
  motifs_dir = paste0(rootDir, "output/motifOutput/motifs_by_orthogroup/summarized_by_OG_500")
)

mats_to_df <- function(mat) {
  mat <- as.data.frame(mat)
  mat$assemblyID <- rownames(mat)
  return(mat)
}

df.list <- lapply(mat.list, mats_to_df)
# Combine into a single df
combined_df <- rbindlist(df.list, use.names = TRUE, fill = TRUE)
```

``` {r}
## Calculate motif occurrence rates for each assembly
all.motifs.by.taxa <- split(combined_df, combined_df$assemblyID)
og.counts <- lapply(all.motifs.by.taxa, nrow)

calculateMotifOccurrenceRates <- function(mat, og.count) {
  # Sum motifs across all orthogroups
  sums <- colSums(mat[,1:(ncol(mat) - 1)], na.rm = TRUE) # for candidate list
  # Divide by number of orthogroups represented in the assembly
  occurrence.rates <- sums / og.count
  # join with assemblyID
  results <- c(mat$assemblyID[1], occurrence.rates)
  results
  names(results)[1] <- "assemblyID"
  return(results)
}

all.motif.occurrence.list <- mapply(calculateMotifOccurrenceRates,  all.motifs.by.taxa, og.counts)
all.motif.occurrence.rates <- as.data.frame(t(all.motif.occurrence.list)) 
all.motif.occurrence.rates[,-1] <- sapply(all.motif.occurrence.rates[,-1], as.numeric)
# Calculate overall motif density for each assembly
motif.densities <- rowSums(all.motif.occurrence.rates[,2:ncol(all.motif.occurrence.rates)]) %>%
  as.data.frame()
motif.densities$assemblyID <- all.motif.occurrence.rates$assemblyID
names(motif.densities)[1] <- "global.motif.density"
rownames(motif.densities) <- motif.densities$assemblyID
```

``` {r}
library(asreml)

# Prepare data as before
EnvTraitMatrix <- env[,286:295]
rownames(EnvTraitMatrix) <- env$assemblyID

nucPC <- dudi.pca(nucFreqs[,-21], scannf = FALSE, nf = 20)
nucPCaxes <- nucPC$li[,1:5]
rownames(nucPCaxes) <- nucFreqs$assemblyID
colnames(nucPCaxes) <- paste0("nucPC", 1:5)
nucPCaxes <- as.data.frame(nucPCaxes) %>% mutate(assemblyID = nucFreqs$assemblyID)

common_rows <- Reduce(intersect, list(
  rownames(all.motif.occurrence.rates),
  rownames(phyloK),
  rownames(EnvTraitMatrix),
  nucPCaxes$assemblyID
)) %>% sort()

EnvTrait_f    <- EnvTraitMatrix[common_rows, ]
motif_occ_f   <- all.motif.occurrence.rates[common_rows, ]
nucFreqs_f    <- nucPCaxes %>% filter(assemblyID %in% common_rows)
Kphylo_f      <- phyloK[common_rows, common_rows]
motif_dens_f  <- motif.densities[common_rows, ]

input_mat <- as.data.frame(cbind(EnvTrait_f, motif_occ_f)) %>%
  left_join(nucFreqs_f, by = "assemblyID") %>%
  left_join(motif_dens_f, by = "assemblyID") %>%
  mutate(assemblyID = factor(assemblyID)) %>%
  setnames(gsub("-", "_", names(.)))

# Set up for parallel loop
nMotifs    <- ncol(motif_occ_f) - 1
n_traits   <- ncol(EnvTrait_f)
ePC_names  <- colnames(EnvTrait_f)
nCores     <- max(detectCores() - 1, 1)

motifModels <- mclapply(
  X       = seq_len(nMotifs),
  FUN     = function(j) {
    motifID <- colnames(input_mat)[j + n_traits + 1]
    # build formula
    fixed_terms <- paste(c(ePC_names, "global.motif.density", paste0("nucPC", 1:5)), collapse = " + ")
    frm         <- as.formula(paste(motifID, "~", fixed_terms))
    # fit model
    m           <- asreml(fixed = frm, random = ~ vm(assemblyID, Kphylo_f), ai.sing = TRUE, data = input_mat)
    smry        <- summary(m)
    loglik      <- smry$loglik
    vc          <- smry$varcomp$component
    phylo_frac  <- vc[1] / sum(vc[1:2])
    wald        <- wald.asreml(m)
    env_coefs   <- m$coefficients$fixed[2:(1 + n_traits)]
    env_pvals   <- -(pchisq(wald[2:(1 + n_traits), 3], 1, log.p = TRUE, lower.tail = FALSE) / log(10))
    list(
      motifID          = motifID,
      phyloExplained   = phylo_frac,
      envCoefficients  = env_coefs,
      envPvalsLog10    = env_pvals
    )
  },
  mc.cores = nCores
)
```

Process results
``` {r}
# Extract p values
model_output <- mclapply(motifModels, function(x) {
  x <- unlist(x)
  x <- t(x)
  x <- as.data.frame(x)
  names(x) <- c("motif", "phylo_explained", paste0("coef_envPC_", 1:n_traits), paste0("log10pval_envPC_", 1:n_traits))
  return(x)
}, mc.cores = detectCores() - 1)

results <- rbindlist(model_output, fill = T)
head(results)
results_df <- results %>%
  pivot_longer(
    cols = starts_with("coef") | starts_with("log10pval"),
    names_to = c(".value", "ePC"),
    names_pattern = "(coef|log10pval)_envPC_(\\d+)"
  ) %>%
  arrange(motif, ePC) %>%
  as.data.frame()

results_df[,c(2,4,5)] <- lapply(results_df[,c(2,4,5)], as.numeric)
results_df$pval <- 10^(-results_df$log10pval)
results_df$p.fdr <- p.adjust(results_df$pval, method = "fdr")
sorted_results <- arrange(results_df, desc(log10pval))

# Must supply named cols/rows with assembly IDs
write.table(sorted_results, file="/workdir/coh22/poaceae_tfbs/results/model_globalOcc_500bp_envPC1.10.csv", sep = ",", quote = F, row.names = F)
```

# Plot QQ plot
``` {r}
sorted_results <- read.table("/workdir/coh22/poaceae_tfbs/results/model_globalOcc_500bp_envPC1.10.csv",header = TRUE, sep = ",")

PlotQQ <- function(df) {
  # Create observed vs expected p values for plot
  observed_pvals = sort(df$log10pval, decreasing = T)
  observed_p.fdr = p.adjust(10^(-observed_pvals), method = "fdr")
  expected_pvals = qunif(seq(0, 1, length.out = length(observed_pvals) + 2), min = 0, max = 1)  # Generate expected values. Note that we are using length+2
  expected_pvals = expected_pvals[expected_pvals != 0 & expected_pvals != 1]  # Remove the two extra values since they are 0 and 1

  p_df = data.frame(observed = observed_pvals,
                    expected = -log10(expected_pvals),
                    color = ifelse(observed_p.fdr < 0.01, "goldenrod1", "#2C7BB6"))  # Assign color based on p.fdr
  
  ggplot(p_df, aes(x = expected, y = observed, color = color)) +
    geom_point(size = 7, alpha = 0.8) +  # Color determined by 'color' column
    scale_color_identity() +  # Use color values directly
    geom_abline(intercept = 0, slope = 1, color = '#D7191C', linetype = 'dashed', linewidth = 0.8) +  # Dashed red line representing y = x
    labs(
      x = expression("-log"[10]~"Expected p-value"),
      y = expression("-log"[10]~"Observed p-value")
    ) +
    theme_minimal(base_size = 36) + 
    theme(
      axis.title = element_text(face = "bold"), 
      panel.grid.major = element_line(linewidth = 0.5, color = 'grey80'),  # Light gray grid lines
      panel.grid.minor = element_blank() 
    )
}
jpeg(paste0(rootDir, "results/figs/model_globalOcc_500bp_envPC1.10.jpeg"), width = 7, height = 8, units = "in", res = 1500)
PlotQQ(sorted_results)
dev.off()
```
Quantify inflation
``` {r}
# Cut into percentiles
percentiles <- cut(sorted_results$pval, breaks = seq(0, 1, by = 0.01), include.lowest = TRUE, right = FALSE)

# Tabulate and plot
barplot(table(percentiles), main = "P-Value Distribution by Percentile (Global motif occurrence)", xlab = "Percentile", ylab = "Count")

chisq_vals <- qchisq(1 - sorted_results$pval, df = 1)

# Calculate lambda
lambda_gc <- median(chisq_vals) / qchisq(0.5, df = 1)
```

Run models with permulation

``` {r}
top_model_list <- dplyr::filter(sorted_results, p.fdr < 0.01) %>%
  dplyr::select(c("motif", "ePC")) %>%
  mutate(OG = rep("global", nrow(.))) %>%
  split(seq(nrow(.))) # produces a list of rows
  

Run_Permulations <- function(model_list, input_df, tree, n_perm) {
  # load libraries once
  library(parallel); library(geiger); library(dplyr); library(data.table); library(asreml); library(ape)
  source(file.path(rootDir, "src/08_associationModeling/Permulate.R"))
  asreml.options(verbose = FALSE)

  # Set up logging
  logfile <- file.path(rootDir, "output/perm_output_log.txt")
  if (file.exists(logfile)) file.remove(logfile)
  log_to_file <- function(msg) {
    ts <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")
    write(paste(ts, msg), logfile, append = TRUE)
  }

  # Prep data
  common   <- intersect(input_df$assemblyID, rownames(phyloK))
  K_sub    <- phyloK[common, common]
  tree_sub <- drop.tip(tree, setdiff(tree$tip.label, common)) # subset tree
  tree_rt  <- midpoint.root(tree_sub) # root with midpoint
  tree_rt$edge.length[is.na(tree_rt$edge.length)] <- 0.1 # coerce NA branch lengths
  tree_res <- multi2di(tree_rt) # resolve multichotomies randomly

  nCores <- max(detectCores() - 1, 1)

  # Run models in parallel
  results <- mclapply(model_list, function(mdl) {
    ogID        <- mdl[["OG"]]
    motif       <- mdl[["motif"]]
    motif_clean <- gsub("-", "_", motif)
    envPC       <- paste0("envPC_", mdl[["ePC"]])
    log_to_file(paste("Permulating", ogID, motif, envPC))

    # Prep dataframe for model
    clean_df <- input_df %>%
      transmute(
        OG         = "global",
        assemblyID = assemblyID,
        motif_val  = .data[[motif_clean]],
        across(c(1:10, 47:52))
      ) %>%
      rename(!!motif_clean := motif_val) %>%
      filter(assemblyID %in% common)

    # Run permulation
    tryCatch(
      permulate(clean_df, motif_clean, envPC, tree_res, K_sub, n_perm),
      error = function(e) { log_to_file(e$message); e }
    )
  }, mc.cores = nCores)

  names(results) <- vapply(model_list, `[[`, "", "OG")
  results
}

# Run across top hits
perm_top_hits_global <- Run_Permulations(top_model_list, input_mat, tree, 1000)

save(perm_top_hits_global, file = paste0(rootDir, "output/models/permulated_1k_globalTopHits_500bpUpstream.RData"))


# Process output data
load(paste0(rootDir, "output/models/permulated_1k_globalTopHits_500bpUpstream.RData"))
perm_df <- mclapply(perm_top_hits_global, as.data.frame, mc.cores = detectCores() - 1) %>%
  rbindlist() %>%
  rowwise() %>%
  mutate(across(
      phylo_explained:last_col(),
      ~ as.numeric(.))) %>%
  mutate(
    waldStat = get(paste0("waldStat_", focal_predVar)),
    coef = get(paste0("coef_", focal_predVar)),
    pval = get(paste0("pval_log10_", focal_predVar))
  ) %>%
  ungroup() %>%
  select(OG, responseVar, focal_predVar, model, phylo_explained, waldStat, coef, pval) %>%
  mutate(model_class = if_else(model == "empirical", "empirical", "perm")) 

perm_pvals <- perm_df %>%
  group_by(OG, responseVar, focal_predVar) %>%
  dplyr::reframe(
    empirical_waldStat = waldStat[model_class == "empirical"],
    pval_permulatedNull = mean(abs(waldStat[model_class == "perm"]) >= abs(empirical_waldStat))
  ) %>%
  dplyr::select(OG, responseVar, focal_predVar, pval_permulatedNull)

emp_models <- perm_df %>%
  filter(model_class == "empirical")

perm_models <- perm_df %>%
  filter(model_class == "perm")

perm_hists <- ggplot(data = perm_models, aes(x = waldStat)) +
  geom_histogram() +
  geom_vline(
    data = emp_models,
    aes(xintercept = waldStat),
    color = "red", linetype = "dashed", size = 1
  ) +
  facet_wrap(
    ~ responseVar + focal_predVar,
    scales = "free",
    ncol = 2
  ) +
  labs(
    x = "Permulated Wald Statistic",
    y = "Count",
    title = "Permulated null distributions vs observed for motif occurrence rate association models"
  ) +
  theme_minimal()
perm_hists
```
